name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang llvm

    - name: Install llvm-ar
      run: |
        # The 'llvm' package doesn't include llvm-ar. We need to install the
        # tools package. To do this robustly, we first find the major version of
        # the installed llvm package.
        LLVM_VERSION=$(llvm-config --version | cut -d'.' -f1)
        echo "Detected LLVM version: $LLVM_VERSION"

        # Now, install the corresponding version-specific tools package.
        sudo apt-get install -y "llvm-$LLVM_VERSION-tools"

        # Verify that llvm-ar is now available
        which llvm-ar

    - name: Run the build script
      run: python main.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git add output/*
        git commit -m "Update build status" || echo "No changes to commit"
        git push
